// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SyncListMicroSIP.Data;

#nullable disable

namespace SyncListMicroSIP.Migrations
{
    [DbContext(typeof(ContactDbContext))]
    [Migration("20250521230350_updateFirstMigration")]
    partial class updateFirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SyncListMicroSIP.Models.Contact", b =>
                {
                    b.Property<string>("Number")
                        .HasMaxLength(500)
                        .HasColumnType("varchar");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("varchar");

                    b.Property<string>("Comment")
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("varchar");

                    b.Property<string>("Firstname")
                        .HasMaxLength(100)
                        .HasColumnType("varchar");

                    b.Property<string>("Info")
                        .HasMaxLength(500)
                        .HasColumnType("varchar");

                    b.Property<string>("Lastname")
                        .HasMaxLength(100)
                        .HasColumnType("varchar");

                    b.Property<string>("Mobile")
                        .HasMaxLength(20)
                        .HasColumnType("varchar");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar");

                    b.Property<int>("Presence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int>("Starred")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("State")
                        .HasMaxLength(100)
                        .HasColumnType("varchar");

                    b.Property<string>("Zip")
                        .HasMaxLength(20)
                        .HasColumnType("varchar");

                    b.HasKey("Number");

                    b.ToTable("Contact", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
